version: 2
jobs:
  build:
    docker:
      - image: $DOCKER_HUB_REPO
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PW
    working_directory: /work
    steps:
      - run: git clone $CIRCLE_REPOSITORY_URL
      - run: echo "hello"
      - run: ls /
      - run: ls /work
      - run: env
      - run: make -C /tiny_rv/core TARGET=fetch veri
