version: 2
jobs:
  build:
    docker:
      - image: $DOCKER_HUB_REPO
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PW
    steps:
      - run: echo "hello"
      - run: ls /
      - run: ls /work
      - run: env
