version: 2
jobs:
  build:
    docker:
      - image: himaaaatti/nsl_docker
        auth:
          username: himaaaatti
          password: $DOCKER_HUB_PW
    steps:
      - checkout
      - run: echo "hello world"

