version: 2
jobs:
  build:
    docker:
      - image: $DOCKER_HUB_REPO
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PW
    working_directory: /work
    steps:
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git clone $CIRCLE_REPOSITORY_URL
      - run: echo "hello"
      - run: ls /
      - run: ls /work
      - run: env
      - run: make -C /work/tiny_rv/core TARGET=fetch veri
