version: 2
jobs:
  build:
    machine: true
    working_directory: ~/tiny_rv
    steps:
      - checkout
      - run: |
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
          docker run $DOCKER_HUB_REPO ls
