version: 2
jobs:
  build:
    docker:
      - image: $DOCKER_HUB_REPO
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PW
    working_directory: /work
    steps:
      - run: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run: git clone $CIRCLE_REPOSITORY_URL

      - run: make -C /work/tiny_rv/core TARGET=control_status_register_tb veri
      - run: make -C /work/tiny_rv/core TARGET=csr_manager veri
      - run: make -C /work/tiny_rv/core TARGET=fetch veri
      - run: make -C /work/tiny_rv/core TARGET=integer_arithmetic_logic veri
      - run: make -C /work/tiny_rv/core TARGET=integer_register veri
      - run: make -C /work/tiny_rv/core TARGET=tiny_rv veri
